kind: Service
apiVersion: v1
metadata:
  name: threads
spec:
  type: LoadBalancer
  selector:
    app: threads
  ports:
  - protocol: TCP
    port: 31000
    nodePort: 31000

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: threads
  labels:
    app: threads
spec:
  replicas: 2
  selector:
    matchLabels:
      app: threads
  template:
    metadata:
      labels:
        app: threads
    spec:
      containers:
      - name: threads
        image: hemanth224/threads
        ports:
        - containerPort: 31000
